language: node_js
node_js:
  - "9.3.0"

script:
  # run units tests
  - npm test

before_deploy:
  # run webpack to build the static pages to deploy
  - npm run build
  # file to tell GitHub pages not to try to run jekyll stuff (can break urls)
  - touch dist/.nojekyll
  # github pages needs this file so it knows vis.siggame.io is the domain name
  - echo vis.siggame.io >> dist/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  verbose: true
  local-dir: dist/
  github-token: $GITHUB_TOKEN
  on:
    branch: master
