language: node_js
node_js:
  - "9.3.0"

script:
  # run units tests
  - npm test

before_deploy:
  # run webpack to build the static pages to deploy
  - npm run build
  # github pages needs this file so it knows vis.siggame.io is the domain name
  - echo vis.siggame.io >> built/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GH_TOKEN
  on:
    branch: master
