language: node_js
node_js:
  - "8.5.0"

before_deploy:
  # run webpack to build the static pages to deploy
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: built/
  github_token: $GH_TOKEN
  on:
    branch: master
